const RuntimeEvents = {
    // Session
    SESSION_STARTED: "SESSION_STARTED",
    SESSION_ENDED: "SESSION_ENDED",
    SESSION_PAUSED: "SESSION_PAUSED",
     SESSION_RESUMED: "SESSION_RESUMED",
    // Package
    PACKAGE_LOADED: "PACKAGE_LOADED",

    // Navigation
    SCREEN_CHANGED: "SCREEN_CHANGED",
    ACTIVITY_STARTED: "ACTIVITY_STARTED",
    ACTIVITY_COMPLETED: "ACTIVITY_COMPLETED",

    // Media
    VIDEO_COMPLETED: "VIDEO_COMPLETED",
    AUDIO_COMPLETED: "AUDIO_COMPLETED",

    // Quiz
    QUIZ_COMPLETED: "QUIZ_COMPLETED",
    QUIZ_FAILED: "QUIZ_FAILED",

    // Speaking
    SPEAKING_COMPLETED: "SPEAKING_COMPLETED",

    // Experience
    EXPERIENCE_COMPLETED: "EXPERIENCE_COMPLETED",

    // Runtime
    RUNTIME_ERROR: "RUNTIME_ERROR",
    EXPERIENCE_LOADED: "EXPERIENCE_LOADED",
    SCREEN_COMPLETED: "SCREEN_COMPLETED",
    SESSION_RESUMED: "SESSION_RESUMED"
};

export default RuntimeEvents;